import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
  OrchestratorRunCreatedPayload as ContractsOrchestratorRunCreatedPayloadSchema,
  OrchestratorRunMessageAddedPayload as ContractsOrchestratorRunMessageAddedPayloadSchema,
  OrchestratorRunSynthesisSetPayload as ContractsOrchestratorRunSynthesisSetPayloadSchema,
  OrchestratorLaneCreatedPayload as ContractsOrchestratorLaneCreatedPayloadSchema,
  OrchestratorLaneDispatchedPayload as ContractsOrchestratorLaneDispatchedPayloadSchema,
  OrchestratorLaneStatusSetPayload as ContractsOrchestratorLaneStatusSetPayloadSchema,
  OrchestratorLaneDependencyUpsertedPayload as ContractsOrchestratorLaneDependencyUpsertedPayloadSchema,
  OrchestratorArtifactUpsertedPayload as ContractsOrchestratorArtifactUpsertedPayloadSchema,
  OrchestratorVerificationRequestedPayload as ContractsOrchestratorVerificationRequestedPayloadSchema,
  OrchestratorVerificationUpsertedPayload as ContractsOrchestratorVerificationUpsertedPayloadSchema,
  OrchestratorApprovalRequestedPayload as ContractsOrchestratorApprovalRequestedPayloadSchema,
  OrchestratorApprovalResolvedPayload as ContractsOrchestratorApprovalResolvedPayloadSchema,
  OrchestratorProcessRuleProposedPayload as ContractsOrchestratorProcessRuleProposedPayloadSchema,
  OrchestratorProcessRuleStatusSetPayload as ContractsOrchestratorProcessRuleStatusSetPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
export const OrchestratorRunCreatedPayload = ContractsOrchestratorRunCreatedPayloadSchema;
export const OrchestratorRunMessageAddedPayload = ContractsOrchestratorRunMessageAddedPayloadSchema;
export const OrchestratorRunSynthesisSetPayload = ContractsOrchestratorRunSynthesisSetPayloadSchema;
export const OrchestratorLaneCreatedPayload = ContractsOrchestratorLaneCreatedPayloadSchema;
export const OrchestratorLaneDispatchedPayload = ContractsOrchestratorLaneDispatchedPayloadSchema;
export const OrchestratorLaneStatusSetPayload = ContractsOrchestratorLaneStatusSetPayloadSchema;
export const OrchestratorLaneDependencyUpsertedPayload =
  ContractsOrchestratorLaneDependencyUpsertedPayloadSchema;
export const OrchestratorArtifactUpsertedPayload = ContractsOrchestratorArtifactUpsertedPayloadSchema;
export const OrchestratorVerificationRequestedPayload =
  ContractsOrchestratorVerificationRequestedPayloadSchema;
export const OrchestratorVerificationUpsertedPayload =
  ContractsOrchestratorVerificationUpsertedPayloadSchema;
export const OrchestratorApprovalRequestedPayload = ContractsOrchestratorApprovalRequestedPayloadSchema;
export const OrchestratorApprovalResolvedPayload = ContractsOrchestratorApprovalResolvedPayloadSchema;
export const OrchestratorProcessRuleProposedPayload =
  ContractsOrchestratorProcessRuleProposedPayloadSchema;
export const OrchestratorProcessRuleStatusSetPayload =
  ContractsOrchestratorProcessRuleStatusSetPayloadSchema;
